export const AXES = {
  C1: { id: "C1", name: "Economic Control", pole_negative: "State-Directed", pole_positive: "Market-Directed" },
  C2: { id: "C2", name: "Economic Equality", pole_negative: "Redistributionist", pole_positive: "Property Rights" },
  C3: { id: "C3", name: "Coercive Power", pole_negative: "Security/Order", pole_positive: "Civil Liberties" },
  C4: { id: "C4", name: "Where Power Sits", pole_negative: "Centralized", pole_positive: "Localized" },
  C5: { id: "C5", name: "Cultural Orientation", pole_negative: "Traditionalist", pole_positive: "Progressivist" },
  C6: { id: "C6", name: "Group Boundaries", pole_negative: "Particularist", pole_positive: "Universalist" },
  C7: { id: "C7", name: "Sovereignty Scope", pole_negative: "Sovereigntist", pole_positive: "Integrationist" },
  C8: { id: "C8", name: "Technology Stance", pole_negative: "Tech-Skeptical", pole_positive: "Tech-Solutionist" },
  C9: { id: "C9", name: "Nature's Moral Weight", pole_negative: "Anthropocentric", pole_positive: "Ecocentric" },
  C10: { id: "C10", name: "Moral Foundation", pole_negative: "Moral Universalist", pole_positive: "Moral Pluralist" },
  F1: { id: "F1", name: "Change Strategy", pole_negative: "Gradualist", pole_positive: "Radical", is_facet: true },
  F2: { id: "F2", name: "Institutional Trust", pole_negative: "Trusting", pole_positive: "Skeptical", is_facet: true },
  F3: { id: "F3", name: "Justice Style", pole_negative: "Retributive", pole_positive: "Restorative", is_facet: true }
} as const

export type AxisId = keyof typeof AXES

export type Item = {
  id: number
  order: number
  axis: AxisId
  key: 1 | -1
  text: string
}

export const ITEMS: Item[] = [
  { id: 1, order: 47, axis: "C7", key: -1, text: "A nation must control its own borders and immigration without outside interference." },
  { id: 2, order: 12, axis: "C2", key: -1, text: "Narrowing the gap between rich and poor should be a central goal of economic policy." },
  { id: 3, order: 83, axis: "F2", key: 1, text: "Major institutions—government, media, corporations—routinely mislead the public to serve their own interests." },
  { id: 4, order: 29, axis: "C4", key: 1, text: "Local communities should have the final word on matters like zoning, schooling, and policing." },
  { id: 5, order: 71, axis: "C9", key: 1, text: "Ecosystems and species have intrinsic value that does not depend on their usefulness to humans." },
  { id: 6, order: 3, axis: "C1", key: 1, text: "Prices for essential goods should be determined by supply and demand, not government regulation." },
  { id: 7, order: 56, axis: "C8", key: -1, text: "Technology tends to create new problems as fast as it solves existing ones." },
  { id: 8, order: 38, axis: "C5", key: 1, text: "Society benefits when people question inherited customs and experiment with new ways of living." },
  { id: 9, order: 91, axis: "F3", key: 1, text: "The primary goal of justice should be repairing harm and reintegrating offenders into society." },
  { id: 10, order: 65, axis: "C8", key: 1, text: "Most major problems—health, poverty, climate—can be solved primarily through technological innovation." },
  { id: 11, order: 22, axis: "C3", key: 1, text: "Protecting individual privacy is more important than making law enforcement's job easier." },
  { id: 12, order: 78, axis: "C10", key: -1, text: "Some actions are objectively wrong regardless of what any culture or individual believes." },
  { id: 13, order: 44, axis: "C6", key: -1, text: "People naturally and rightly owe more loyalty to their own community than to outsiders." },
  { id: 14, order: 8, axis: "C1", key: -1, text: "The state should directly control strategic industries like energy, transportation, and banking." },
  { id: 15, order: 87, axis: "F2", key: -1, text: "On balance, the institutions that run society are genuinely trying to do the right thing." },
  { id: 16, order: 33, axis: "C4", key: -1, text: "National standards are necessary to guarantee equal rights and services everywhere." },
  { id: 17, order: 52, axis: "C7", key: 1, text: "International courts should be able to override national laws that violate human rights." },
  { id: 18, order: 17, axis: "C2", key: 1, text: "People have a fundamental right to keep what they earn, regardless of how much others have." },
  { id: 19, order: 61, axis: "C8", key: 1, text: "Automation and AI will create more prosperity than they destroy over time." },
  { id: 20, order: 95, axis: "F3", key: -1, text: "Wrongdoers deserve punishment proportional to the severity of their offense." },
  { id: 21, order: 26, axis: "C3", key: -1, text: "Strict law enforcement and visible policing are necessary to maintain public safety." },
  { id: 22, order: 74, axis: "C9", key: -1, text: "Nature's primary value lies in the resources and services it provides to human beings." },
  { id: 23, order: 41, axis: "C5", key: -1, text: "Longstanding traditions carry wisdom that modern generations too easily dismiss." },
  { id: 24, order: 1, axis: "C1", key: 1, text: "Private enterprise generally delivers goods and services more efficiently than government agencies." },
  { id: 25, order: 81, axis: "F1", key: 1, text: "Sometimes dramatic, disruptive action is the only way to overcome entrenched injustice." },
  { id: 26, order: 48, axis: "C7", key: -1, text: "Trade agreements that constrain domestic policy undermine democratic self-determination." },
  { id: 27, order: 13, axis: "C2", key: -1, text: "A universal basic income, funded by taxing wealth, would create a more just society." },
  { id: 28, order: 68, axis: "C8", key: 1, text: "Genetic engineering of crops and humans should be embraced as a tool for improving life." },
  { id: 29, order: 36, axis: "C4", key: -1, text: "Some issues are too important to leave to local jurisdictions with varying capacities." },
  { id: 30, order: 84, axis: "F2", key: 1, text: "Official experts often conceal important information or present biased conclusions." },
  { id: 31, order: 23, axis: "C3", key: 1, text: "People should be free to express offensive views without legal penalty." },
  { id: 32, order: 57, axis: "C8", key: -1, text: "Society has become dangerously dependent on complex systems that few people understand." },
  { id: 33, order: 92, axis: "F3", key: 1, text: "Bringing victims and offenders together to seek understanding produces better outcomes than punishment alone." },
  { id: 34, order: 5, axis: "C1", key: 1, text: "Governments should allow failing businesses to collapse rather than intervene with bailouts." },
  { id: 35, order: 75, axis: "C9", key: -1, text: "When human well-being and environmental preservation conflict, human needs should come first." },
  { id: 36, order: 42, axis: "C5", key: -1, text: "Stable families built on time-tested structures are the foundation of a healthy society." },
  { id: 37, order: 79, axis: "C10", key: -1, text: "Moral truths exist and can be discovered through reason, experience, or revelation." },
  { id: 38, order: 30, axis: "C4", key: 1, text: "States or provinces should be able to pass laws that differ from national policy." },
  { id: 39, order: 53, axis: "C7", key: 1, text: "Nations should transfer some sovereignty to global institutions to address climate change." },
  { id: 40, order: 18, axis: "C2", key: 1, text: "Inheritance taxes unfairly prevent families from passing on what they have built." },
  { id: 41, order: 88, axis: "F2", key: -1, text: "Most professionals—doctors, scientists, judges—can be trusted to act with integrity." },
  { id: 42, order: 9, axis: "C1", key: -1, text: "Central planning can distribute resources more fairly than markets do." },
  { id: 43, order: 62, axis: "C8", key: 1, text: "New technologies should generally be deployed quickly; we can address problems as they arise." },
  { id: 44, order: 39, axis: "C5", key: 1, text: "Traditional expectations about gender and family are outdated constraints that should be discarded." },
  { id: 45, order: 96, axis: "F3", key: -1, text: "A justice system that does not punish crime fails to uphold moral order." },
  { id: 46, order: 27, axis: "C3", key: -1, text: "Governments should be able to detain terrorism suspects without trial when security demands it." },
  { id: 47, order: 45, axis: "C6", key: -1, text: "A society that does not put its own members first will eventually be unable to help anyone." },
  { id: 48, order: 72, axis: "C9", key: 1, text: "Economic development should be constrained when it threatens biodiversity or ecosystem health." },
  { id: 49, order: 82, axis: "F1", key: 1, text: "Protest and civil disobedience are legitimate tools when institutions fail to respond." },
  { id: 50, order: 14, axis: "C2", key: -1, text: "Large concentrations of private wealth are corrosive to democracy and social cohesion." },
  { id: 51, order: 34, axis: "C4", key: -1, text: "Only a strong central government can coordinate responses to large-scale challenges." },
  { id: 52, order: 58, axis: "C8", key: -1, text: "Some technologies—certain weapons, surveillance tools, AI systems—should never have been built." },
  { id: 53, order: 49, axis: "C7", key: -1, text: "Supranational bodies like the UN, EU, or WTO have accumulated too much power over national affairs." },
  { id: 54, order: 24, axis: "C3", key: 1, text: "Citizens should have access to strong encryption without government back-doors." },
  { id: 55, order: 76, axis: "C9", key: -1, text: "Protecting endangered species is not worth major economic sacrifice." },
  { id: 56, order: 85, axis: "F2", key: 1, text: "The people who run powerful institutions are more interested in protecting their position than serving the public." },
  { id: 57, order: 43, axis: "C5", key: -1, text: "Rapid cultural change destabilizes communities and erodes the values that bind people together." },
  { id: 58, order: 6, axis: "C1", key: 1, text: "Competition between private companies benefits consumers more than public alternatives would." },
  { id: 59, order: 93, axis: "F3", key: 1, text: "Most people who commit crimes need support and rehabilitation, not cages." },
  { id: 60, order: 19, axis: "C2", key: 1, text: "High taxes on top earners discourage the productive effort that benefits everyone." },
  { id: 61, order: 80, axis: "C10", key: -1, text: "Without grounding in universal principles, ethics becomes arbitrary and unstable." },
  { id: 62, order: 31, axis: "C4", key: 1, text: "Decisions made closest to the people affected tend to produce better outcomes." },
  { id: 63, order: 54, axis: "C7", key: 1, text: "Free movement of people across borders ultimately benefits both migrants and host countries." },
  { id: 64, order: 10, axis: "C1", key: -1, text: "Essential services (water, electricity, internet) should be publicly owned and operated." },
  { id: 65, order: 66, axis: "C8", key: -1, text: "The unintended consequences of new technologies are often worse than the problems they address." },
  { id: 66, order: 40, axis: "C5", key: 1, text: "Moral progress often requires abandoning practices that previous generations considered normal." },
  { id: 67, order: 28, axis: "C3", key: -1, text: "Some speech is so harmful that it should be legally prohibited." },
  { id: 68, order: 86, axis: "F1", key: -1, text: "Lasting reform comes through patient, incremental work within existing institutions." },
  { id: 69, order: 73, axis: "C9", key: 1, text: "Future generations and non-human life deserve moral consideration equal to living humans." },
  { id: 70, order: 46, axis: "C6", key: -1, text: "It is reasonable to prioritize people who share your culture or heritage in hiring and assistance." },
  { id: 71, order: 15, axis: "C2", key: -1, text: "Society has an obligation to ensure that no one falls below a decent standard of living." },
  { id: 72, order: 97, axis: "F3", key: -1, text: "Accountability means facing real consequences, not just dialogue and reconciliation." },
  { id: 73, order: 35, axis: "C4", key: -1, text: "Too much local autonomy leads to fragmentation and unequal treatment across regions." },
  { id: 74, order: 63, axis: "C6", key: 1, text: "Our obligations to strangers across the world are just as strong as those to our neighbors." },
  { id: 75, order: 50, axis: "C7", key: -1, text: "Citizens of a country, not international bodies, should decide the laws that govern them." },
  { id: 76, order: 89, axis: "F2", key: -1, text: "Democratic institutions, despite their flaws, generally produce fair outcomes over time." },
  { id: 77, order: 25, axis: "C3", key: 1, text: "The right to protest, even disruptively, is essential to a free society." },
  { id: 78, order: 7, axis: "C1", key: -1, text: "Governments should set price controls on necessities like housing, food, and medicine." },
  { id: 79, order: 77, axis: "C10", key: 1, text: "What counts as right and wrong depends largely on cultural context and historical circumstances." },
  { id: 80, order: 44, axis: "C5", key: -1, text: "There is value in preserving customs and rituals even when their original purpose has faded." },
  { id: 81, order: 20, axis: "C2", key: 1, text: "Wealth inequality is a natural outcome of differences in talent, effort, and choices." },
  { id: 82, order: 94, axis: "F1", key: -1, text: "Revolutionary movements usually cause more suffering than the injustices they aimed to correct." },
  { id: 83, order: 64, axis: "C6", key: 1, text: "Moral rules should apply equally to all people regardless of nationality, ethnicity, or religion." },
  { id: 84, order: 55, axis: "C7", key: 1, text: "Global problems require global governance that nations cannot opt out of." },
  { id: 85, order: 32, axis: "C4", key: 1, text: "Regions should be allowed to experiment with different policies rather than follow a single national model." },
  { id: 86, order: 90, axis: "C3", key: -1, text: "Schools and employers should enforce conduct codes even when they limit personal expression." },
  { id: 87, order: 69, axis: "C9", key: 1, text: "Humans have a duty to preserve wild nature even at significant cost to our own prosperity." },
  { id: 88, order: 98, axis: "C10", key: 1, text: "There is no single correct moral framework; reasonable people can hold fundamentally different values." },
  { id: 89, order: 83, axis: "F1", key: 1, text: "Fundamental change requires confrontation, not negotiation with those who benefit from the status quo." },
  { id: 90, order: 67, axis: "C6", key: 1, text: "Aid and assistance should be allocated based on need, not on shared identity or proximity." },
  { id: 91, order: 4, axis: "C10", key: 1, text: "Morality is a human construction that evolves as societies develop new understandings." },
  { id: 92, order: 70, axis: "C9", key: -1, text: "The natural world exists as a resource for human use and flourishing." },
  { id: 93, order: 37, axis: "C5", key: 1, text: "Cultural norms should evolve to reflect new understandings of identity and relationships." },
  { id: 94, order: 16, axis: "C10", key: 1, text: "Ethical disagreements often cannot be resolved because people are starting from incompatible premises." },
  { id: 95, order: 59, axis: "C6", key: 1, text: "National borders are morally arbitrary lines that shouldn't determine who deserves our concern." },
  { id: 96, order: 2, axis: "C10", key: -1, text: "Across all cultures and eras, certain core moral standards remain constant." },
  { id: 97, order: 60, axis: "C6", key: -1, text: "Strong group identity and mutual obligation within communities produce better outcomes than abstract universalism." },
  { id: 98, order: 11, axis: "F1", key: -1, text: "Stability and continuity are valuable even when change is desirable in principle." }
]

export const ORDERED_ITEMS = [...ITEMS].sort((a, b) => a.order - b.order)

export type FlavorArchetype = {
  id: string
  name: string
  description: string
  color: string
  components: { axis: AxisId; direction: 1 | -1 | 0; weight: number }[]
}

export const FLAVOR_ARCHETYPES: FlavorArchetype[] = [
  { id: "revolutionary_socialist", name: "Revolutionary Socialist", description: "Believes radical action is necessary to achieve economic equality and dismantle capitalist structures.", color: "#D32F2F", components: [{ axis: "C2", direction: -1, weight: 1 }, { axis: "F1", direction: 1, weight: 1 }] },
  { id: "social_democrat", name: "Social Democrat", description: "Supports redistribution and social programs through gradual reform within democratic institutions.", color: "#E91E63", components: [{ axis: "C2", direction: -1, weight: 1 }, { axis: "F1", direction: -1, weight: 1 }] },
  { id: "libertarian_capitalist", name: "Libertarian Capitalist", description: "Champions free markets, property rights, and minimal state intervention in both economic and personal life.", color: "#FFC107", components: [{ axis: "C1", direction: 1, weight: 1 }, { axis: "C2", direction: 1, weight: 0.8 }, { axis: "C3", direction: 1, weight: 1 }] },
  { id: "authoritarian_capitalist", name: "Authoritarian Capitalist", description: "Supports free markets and property rights but accepts strong state power to maintain order and stability.", color: "#FF9800", components: [{ axis: "C1", direction: 1, weight: 1 }, { axis: "C3", direction: -1, weight: 1 }] },
  { id: "state_socialist", name: "State Socialist", description: "Advocates for centralized state control of the economy with strong institutional authority.", color: "#B71C1C", components: [{ axis: "C1", direction: -1, weight: 1 }, { axis: "C2", direction: -1, weight: 0.8 }, { axis: "F2", direction: -1, weight: 0.7 }] },
  { id: "establishment_progressive", name: "Establishment Progressive", description: "Supports cultural change and social progress through existing institutions and gradual reform.", color: "#2196F3", components: [{ axis: "C5", direction: 1, weight: 1 }, { axis: "F1", direction: -1, weight: 0.8 }, { axis: "F2", direction: -1, weight: 0.8 }] },
  { id: "radical_progressive", name: "Radical Progressive", description: "Believes fundamental cultural transformation requires confrontational tactics and systemic change.", color: "#9C27B0", components: [{ axis: "C5", direction: 1, weight: 1 }, { axis: "F1", direction: 1, weight: 1 }] },
  { id: "traditional_conservative", name: "Traditional Conservative", description: "Values inherited customs, stable institutions, and gradual organic change over social engineering.", color: "#3F51B5", components: [{ axis: "C5", direction: -1, weight: 1 }, { axis: "F1", direction: -1, weight: 1 }, { axis: "F2", direction: -1, weight: 0.6 }] },
  { id: "reactionary", name: "Reactionary", description: "Seeks to restore a previous social order through decisive action against modern changes.", color: "#1A237E", components: [{ axis: "C5", direction: -1, weight: 1 }, { axis: "F1", direction: 1, weight: 1 }] },
  { id: "populist_nationalist", name: "Populist Nationalist", description: "Distrusts elites and institutions while prioritizing national sovereignty and in-group loyalty.", color: "#FF5722", components: [{ axis: "C6", direction: -1, weight: 1 }, { axis: "C7", direction: -1, weight: 1 }, { axis: "F2", direction: 1, weight: 1 }] },
  { id: "cosmopolitan_liberal", name: "Cosmopolitan Liberal", description: "Embraces universal human rights, international cooperation, and open borders.", color: "#00BCD4", components: [{ axis: "C6", direction: 1, weight: 1 }, { axis: "C7", direction: 1, weight: 1 }, { axis: "C3", direction: 1, weight: 0.6 }] },
  { id: "civic_nationalist", name: "Civic Nationalist", description: "Values national sovereignty and identity through shared civic values rather than ethnic ties.", color: "#607D8B", components: [{ axis: "C7", direction: -1, weight: 1 }, { axis: "F2", direction: -1, weight: 0.5 }] },
  { id: "techno_optimist", name: "Techno-Optimist", description: "Believes technology can solve humanity's greatest challenges and should be rapidly deployed.", color: "#4CAF50", components: [{ axis: "C8", direction: 1, weight: 1 }, { axis: "C1", direction: 1, weight: 0.5 }] },
  { id: "techno_skeptic", name: "Techno-Skeptic", description: "Warns against technological hubris and advocates for caution and human-scale solutions.", color: "#795548", components: [{ axis: "C8", direction: -1, weight: 1 }, { axis: "C5", direction: -1, weight: 0.5 }] },
  { id: "deep_ecologist", name: "Deep Ecologist", description: "Holds that nature has intrinsic value and human civilization must radically reduce its impact.", color: "#1B5E20", components: [{ axis: "C9", direction: 1, weight: 1 }, { axis: "F1", direction: 1, weight: 0.7 }] },
  { id: "green_reformist", name: "Green Reformist", description: "Supports environmental protection through market mechanisms, regulation, and gradual policy change.", color: "#66BB6A", components: [{ axis: "C9", direction: 1, weight: 1 }, { axis: "F1", direction: -1, weight: 0.8 }, { axis: "F2", direction: -1, weight: 0.5 }] },
  { id: "eco_sovereigntist", name: "Eco-Sovereigntist", description: "Prioritizes ecological stewardship while keeping environmental policy under national control and gradual change.", color: "#2E7D32", components: [{ axis: "C9", direction: 1, weight: 1 }, { axis: "C7", direction: -1, weight: 0.8 }, { axis: "F1", direction: -1, weight: 0.5 }] },
  { id: "communitarian_conservationist", name: "Communitarian Conservationist", description: "Emphasizes protecting local landscapes for the benefit of one's own community, favoring particularist obligations.", color: "#33691E", components: [{ axis: "C9", direction: 1, weight: 1 }, { axis: "C6", direction: -1, weight: 0.9 }, { axis: "F2", direction: -1, weight: 0.4 }] },
  { id: "anthropocentric_developer", name: "Anthropocentric Developer", description: "Prioritizes human welfare and economic development over environmental constraints.", color: "#FF9800", components: [{ axis: "C9", direction: -1, weight: 1 }, { axis: "C8", direction: 1, weight: 0.7 }] },
  { id: "punitive_authoritarian", name: "Punitive Authoritarian", description: "Believes strong state power and harsh punishment are necessary to maintain social order.", color: "#37474F", components: [{ axis: "C3", direction: -1, weight: 1 }, { axis: "F3", direction: -1, weight: 1 }] },
  { id: "restorative_libertarian", name: "Restorative Libertarian", description: "Supports civil liberties and believes justice should focus on repair and reconciliation.", color: "#8BC34A", components: [{ axis: "C3", direction: 1, weight: 1 }, { axis: "F3", direction: 1, weight: 1 }] },
  { id: "localist_communitarian", name: "Localist Communitarian", description: "Emphasizes local self-governance, community bonds, and subsidiarity over centralized control.", color: "#8D6E63", components: [{ axis: "C4", direction: 1, weight: 1 }, { axis: "C6", direction: -1, weight: 0.6 }] },
  { id: "centralist_universalist", name: "Centralist Universalist", description: "Believes strong central authority is needed to ensure equal rights and consistent standards for all.", color: "#5C6BC0", components: [{ axis: "C4", direction: -1, weight: 1 }, { axis: "C6", direction: 1, weight: 0.8 }] },
  { id: "moral_absolutist", name: "Moral Absolutist", description: "Believes in objective moral truths that apply universally regardless of culture or circumstance.", color: "#7E57C2", components: [{ axis: "C10", direction: -1, weight: 1 }] },
  { id: "moral_pluralist", name: "Moral Pluralist", description: "Holds that moral values are culturally constructed and no single framework can claim universal validity.", color: "#AB47BC", components: [{ axis: "C10", direction: 1, weight: 1 }] },
  { id: "anti_establishment_left", name: "Anti-Establishment Left", description: "Combines progressive economics with deep distrust of institutions and support for confrontational tactics.", color: "#C62828", components: [{ axis: "C2", direction: -1, weight: 1 }, { axis: "F2", direction: 1, weight: 1 }, { axis: "F1", direction: 1, weight: 0.8 }] },
  { id: "anti_establishment_right", name: "Anti-Establishment Right", description: "Combines traditional values with deep distrust of institutions and willingness for disruptive action.", color: "#BF360C", components: [{ axis: "C5", direction: -1, weight: 1 }, { axis: "F2", direction: 1, weight: 1 }, { axis: "F1", direction: 1, weight: 0.6 }] },
  { id: "technocratic_centrist", name: "Technocratic Centrist", description: "Trusts experts and institutions to solve problems through evidence-based policy rather than ideology.", color: "#78909C", components: [{ axis: "F2", direction: -1, weight: 1 }, { axis: "F1", direction: -1, weight: 0.8 }, { axis: "C8", direction: 1, weight: 0.6 }] },
  { id: "anarchist", name: "Anarchist / Anti-Statist", description: "Opposes centralized authority in all forms, favoring voluntary association and mutual aid.", color: "#212121", components: [{ axis: "C4", direction: 1, weight: 1 }, { axis: "C3", direction: 1, weight: 1 }, { axis: "F2", direction: 1, weight: 0.8 }] },
  { id: "statist", name: "Statist / Centralist", description: "Believes strong central state authority is necessary and beneficial for society.", color: "#455A64", components: [{ axis: "C4", direction: -1, weight: 1 }, { axis: "C3", direction: -1, weight: 0.8 }, { axis: "F2", direction: -1, weight: 0.6 }] }
]
