// Polyaxis v2.0 constructs: 11 core axes and 7 style facets. Relative to
// v1: C10 Moral Epistemology was split into C10 Moral Objectivity and
// C11 Value Structure; F4 Decision Authority was split into F4 Democratic
// Constraint, F5 Epistemic Authority, and F6 Democratic Mediation; and
// Force & Peace moved from the core-tier F5 slot to F7. Because the F5
// id changed meaning, v1 and v2 results are not comparable; stored
// results carry bank_version to keep the eras separate.
export const AXES = {
  C1: { id: "C1", name: "Economic Coordination", pole_negative: "State-Directed", pole_positive: "Market-Directed" },
  C2: { id: "C2", name: "Distribution & Property", pole_negative: "Redistributionist", pole_positive: "Property-Rights" },
  C3: { id: "C3", name: "Liberty & Public Order", pole_negative: "Security/Order", pole_positive: "Civil Liberties" },
  C4: { id: "C4", name: "Territorial Authority", pole_negative: "Centralized", pole_positive: "Localized" },
  C5: { id: "C5", name: "Cultural Continuity", pole_negative: "Traditionalist", pole_positive: "Progressivist" },
  C6: { id: "C6", name: "Scope of Obligation", pole_negative: "Particularist", pole_positive: "Universalist" },
  C7: { id: "C7", name: "Sovereignty Scope", pole_negative: "Sovereigntist", pole_positive: "Integrationist" },
  C8: { id: "C8", name: "Technology Orientation", pole_negative: "Tech-Cautious", pole_positive: "Tech-Accelerative" },
  C9: { id: "C9", name: "Ecological Moral Standing", pole_negative: "Anthropocentric", pole_positive: "Ecocentric" },
  C10: { id: "C10", name: "Moral Objectivity", pole_negative: "Moral Objectivist", pole_positive: "Moral Contextualist" },
  C11: { id: "C11", name: "Value Structure", pole_negative: "Moral Monist", pole_positive: "Value Pluralist" },
  F1: { id: "F1", name: "Change Strategy", pole_negative: "Gradualist", pole_positive: "Transformative", is_facet: true },
  F2: { id: "F2", name: "Institutional Confidence", pole_negative: "Trusting", pole_positive: "Skeptical", is_facet: true },
  F3: { id: "F3", name: "Justice Style", pole_negative: "Retributive", pole_positive: "Restorative", is_facet: true },
  F4: { id: "F4", name: "Democratic Constraint", pole_negative: "Majoritarian", pole_positive: "Constitutionalist", is_facet: true },
  F5: { id: "F5", name: "Epistemic Authority", pole_negative: "Popular/Elected Judgment", pole_positive: "Expert Delegation", is_facet: true },
  F6: { id: "F6", name: "Democratic Mediation", pole_negative: "Direct Democracy", pole_positive: "Representative Deliberation", is_facet: true },
  F7: { id: "F7", name: "Force & Peace", pole_negative: "Dove", pole_positive: "Hawk", is_facet: true }
} as const

export type AxisId = keyof typeof AXES


export type FlavorArchetype = {
  id: string
  name: string
  description: string
  color: string
  components: { axis: AxisId; direction: 1 | -1 | 0; weight: number }[]
}

export const FLAVOR_ARCHETYPES: FlavorArchetype[] = [
  { id: "revolutionary_socialist", name: "Revolutionary Socialist", description: "Believes radical action is necessary to achieve economic equality and dismantle capitalist structures.", color: "#D32F2F", components: [{ axis: "C2", direction: -1, weight: 1 }, { axis: "F1", direction: 1, weight: 1 }, { axis: "C1", direction: -1, weight: 0.8 }] },
  { id: "social_democrat", name: "Social Democrat", description: "Supports redistribution and social programs through gradual reform within democratic institutions.", color: "#E91E63", components: [{ axis: "C2", direction: -1, weight: 1 }, { axis: "F1", direction: -1, weight: 1 }, { axis: "C1", direction: -1, weight: 0.4 }, { axis: "F6", direction: 1, weight: 0.4 }] },
  { id: "libertarian_capitalist", name: "Libertarian Capitalist", description: "Champions free markets, property rights, and minimal state intervention in both economic and personal life.", color: "#FFC107", components: [{ axis: "C1", direction: 1, weight: 1 }, { axis: "C2", direction: 1, weight: 0.8 }, { axis: "C3", direction: 1, weight: 1 }, { axis: "F5", direction: -1, weight: 0.4 }] },
  { id: "authoritarian_capitalist", name: "Authoritarian Capitalist", description: "Supports free markets and property rights but accepts strong state power to maintain order and stability.", color: "#FF9800", components: [{ axis: "C1", direction: 1, weight: 1 }, { axis: "C3", direction: -1, weight: 1 }, { axis: "F7", direction: 1, weight: 0.5 }] },
  { id: "state_socialist", name: "State Socialist", description: "Advocates for centralized state control of the economy with strong institutional authority.", color: "#B71C1C", components: [{ axis: "C1", direction: -1, weight: 1 }, { axis: "C2", direction: -1, weight: 0.8 }, { axis: "F2", direction: -1, weight: 0.7 }] },
  { id: "establishment_progressive", name: "Establishment Progressive", description: "Supports cultural change and social progress through existing institutions and gradual reform.", color: "#2196F3", components: [{ axis: "C5", direction: 1, weight: 1 }, { axis: "F1", direction: -1, weight: 0.8 }, { axis: "F2", direction: -1, weight: 0.8 }] },
  { id: "radical_progressive", name: "Radical Progressive", description: "Believes fundamental cultural transformation requires confrontational tactics and systemic change.", color: "#9C27B0", components: [{ axis: "C5", direction: 1, weight: 1 }, { axis: "F1", direction: 1, weight: 1 }] },
  { id: "traditional_conservative", name: "Traditional Conservative", description: "Values inherited customs, stable institutions, and gradual organic change over social engineering.", color: "#3F51B5", components: [{ axis: "C5", direction: -1, weight: 1 }, { axis: "F1", direction: -1, weight: 1 }, { axis: "F2", direction: -1, weight: 0.6 }] },
  { id: "reactionary", name: "Reactionary", description: "Seeks to restore a previous social order through decisive action against modern changes.", color: "#1A237E", components: [{ axis: "C5", direction: -1, weight: 1 }, { axis: "F1", direction: 1, weight: 1 }] },
  { id: "populist_nationalist", name: "Populist Nationalist", description: "Distrusts elites and institutions while prioritizing national sovereignty and in-group loyalty.", color: "#FF5722", components: [{ axis: "C6", direction: -1, weight: 1 }, { axis: "C7", direction: -1, weight: 1 }, { axis: "F2", direction: 1, weight: 1 }, { axis: "F4", direction: -1, weight: 0.8 }, { axis: "F5", direction: -1, weight: 0.6 }, { axis: "F6", direction: -1, weight: 0.5 }] },
  { id: "cosmopolitan_liberal", name: "Cosmopolitan Liberal", description: "Embraces universal human rights, international cooperation, and open borders.", color: "#00BCD4", components: [{ axis: "C6", direction: 1, weight: 1 }, { axis: "C7", direction: 1, weight: 1 }, { axis: "C3", direction: 1, weight: 0.6 }] },
  { id: "civic_nationalist", name: "Civic Nationalist", description: "Values national sovereignty and identity through shared civic values rather than ethnic ties.", color: "#607D8B", components: [{ axis: "C7", direction: -1, weight: 1 }, { axis: "C6", direction: 1, weight: 0.4 }, { axis: "F2", direction: -1, weight: 0.5 }] },
  { id: "techno_optimist", name: "Techno-Optimist", description: "Believes technology can solve humanity's greatest challenges and should be rapidly deployed.", color: "#4CAF50", components: [{ axis: "C8", direction: 1, weight: 1 }, { axis: "C1", direction: 1, weight: 0.5 }] },
  { id: "techno_skeptic", name: "Techno-Skeptic", description: "Warns against technological hubris and advocates for caution and human-scale solutions.", color: "#795548", components: [{ axis: "C8", direction: -1, weight: 1 }, { axis: "C5", direction: -1, weight: 0.3 }] },
  { id: "deep_ecologist", name: "Deep Ecologist", description: "Holds that nature has intrinsic value and human civilization must radically reduce its impact.", color: "#1B5E20", components: [{ axis: "C9", direction: 1, weight: 1 }, { axis: "F1", direction: 1, weight: 0.9 }, { axis: "C8", direction: -1, weight: 0.6 }] },
  { id: "green_reformist", name: "Green Reformist", description: "Supports environmental protection through market mechanisms, regulation, and gradual policy change.", color: "#66BB6A", components: [{ axis: "C9", direction: 1, weight: 1 }, { axis: "F1", direction: -1, weight: 0.9 }, { axis: "F2", direction: -1, weight: 0.7 }] },
  { id: "eco_sovereigntist", name: "Eco-Sovereigntist", description: "Prioritizes ecological stewardship while keeping environmental policy under national control and gradual change.", color: "#2E7D32", components: [{ axis: "C9", direction: 1, weight: 1 }, { axis: "C7", direction: -1, weight: 0.9 }, { axis: "F1", direction: -1, weight: 0.7 }] },
  { id: "communitarian_conservationist", name: "Communitarian Conservationist", description: "Emphasizes protecting local landscapes for the benefit of one's own community, favoring particularist obligations.", color: "#33691E", components: [{ axis: "C9", direction: 1, weight: 1 }, { axis: "C6", direction: -1, weight: 0.9 }, { axis: "F2", direction: -1, weight: 0.6 }] },
  { id: "eco_capitalist", name: "Eco-Capitalist", description: "Believes green enterprise and market innovation are the most effective tools for protecting nature.", color: "#00897B", components: [{ axis: "C9", direction: 1, weight: 1 }, { axis: "C1", direction: 1, weight: 0.8 }, { axis: "C8", direction: 1, weight: 0.4 }] },
  { id: "anthropocentric_developer", name: "Anthropocentric Developer", description: "Prioritizes human welfare and economic development over environmental constraints.", color: "#FF9800", components: [{ axis: "C9", direction: -1, weight: 1 }, { axis: "C8", direction: 1, weight: 0.7 }] },
  { id: "punitive_authoritarian", name: "Punitive Authoritarian", description: "Believes strong state power and harsh punishment are necessary to maintain social order.", color: "#37474F", components: [{ axis: "C3", direction: -1, weight: 1 }, { axis: "F3", direction: -1, weight: 1 }] },
  { id: "restorative_libertarian", name: "Restorative Libertarian", description: "Supports civil liberties and believes justice should focus on repair and reconciliation.", color: "#8BC34A", components: [{ axis: "C3", direction: 1, weight: 1 }, { axis: "F3", direction: 1, weight: 1 }] },
  { id: "localist_communitarian", name: "Localist Communitarian", description: "Emphasizes local self-governance, community bonds, and subsidiarity over centralized control.", color: "#8D6E63", components: [{ axis: "C4", direction: 1, weight: 1 }, { axis: "C6", direction: -1, weight: 0.6 }] },
  { id: "centralist_universalist", name: "Centralist Universalist", description: "Believes strong central authority is needed to ensure equal rights and consistent standards for all.", color: "#5C6BC0", components: [{ axis: "C4", direction: -1, weight: 1 }, { axis: "C6", direction: 1, weight: 0.8 }] },
  { id: "moral_absolutist", name: "Moral Absolutist", description: "Believes in objective moral truths that apply universally regardless of culture or circumstance.", color: "#7E57C2", components: [{ axis: "C10", direction: -1, weight: 1 }, { axis: "C11", direction: -1, weight: 0.6 }, { axis: "C6", direction: 1, weight: 0.4 }] },
  { id: "moral_pluralist", name: "Moral Pluralist", description: "Holds that moral values are plural and context-bound, and no single framework can claim universal validity.", color: "#AB47BC", components: [{ axis: "C11", direction: 1, weight: 1 }, { axis: "C10", direction: 1, weight: 0.6 }, { axis: "C6", direction: -1, weight: 0.4 }] },
  { id: "anti_establishment_left", name: "Anti-Establishment Left", description: "Combines progressive economics with deep distrust of institutions and support for confrontational tactics.", color: "#C62828", components: [{ axis: "C2", direction: -1, weight: 1 }, { axis: "F2", direction: 1, weight: 1 }, { axis: "F1", direction: 1, weight: 0.8 }] },
  { id: "anti_establishment_right", name: "Anti-Establishment Right", description: "Combines traditional values with deep distrust of institutions and willingness for disruptive action.", color: "#BF360C", components: [{ axis: "C5", direction: -1, weight: 1 }, { axis: "F2", direction: 1, weight: 1 }, { axis: "F1", direction: 1, weight: 0.6 }] },
  { id: "technocratic_centrist", name: "Technocratic Centrist", description: "Trusts experts and institutions to solve problems through evidence-based policy rather than ideology.", color: "#78909C", components: [{ axis: "F2", direction: -1, weight: 1 }, { axis: "F5", direction: 1, weight: 1 }, { axis: "F1", direction: -1, weight: 0.8 }, { axis: "F6", direction: 1, weight: 0.4 }, { axis: "C8", direction: 1, weight: 0.6 }] },
  { id: "anarchist", name: "Anarchist / Anti-Statist", description: "Opposes centralized authority in all forms, favoring voluntary association and mutual aid.", color: "#212121", components: [{ axis: "C4", direction: 1, weight: 1 }, { axis: "C3", direction: 1, weight: 1 }, { axis: "F2", direction: 1, weight: 0.8 }, { axis: "F6", direction: -1, weight: 0.6 }] },
  { id: "statist", name: "Statist / Centralist", description: "Believes strong central state authority is necessary and beneficial for society.", color: "#455A64", components: [{ axis: "C4", direction: -1, weight: 1 }, { axis: "C3", direction: -1, weight: 0.8 }, { axis: "F2", direction: -1, weight: 0.6 }] },
  { id: "moral_traditionalist", name: "Moral Traditionalist", description: "Grounds politics in enduring moral truths and time-tested ways of life, with firm accountability for wrongdoing.", color: "#4E342E", components: [{ axis: "C5", direction: -1, weight: 1 }, { axis: "C10", direction: -1, weight: 0.8 }, { axis: "C11", direction: -1, weight: 0.4 }, { axis: "F3", direction: -1, weight: 0.4 }] },
  { id: "libertarian_socialist", name: "Libertarian Socialist", description: "Seeks economic equality through decentralized, voluntary cooperation rather than state control.", color: "#AD1457", components: [{ axis: "C2", direction: -1, weight: 1 }, { axis: "C4", direction: 1, weight: 0.8 }, { axis: "C3", direction: 1, weight: 0.8 }] },
  { id: "democratic_populist", name: "Democratic Populist", description: "Believes ordinary citizens, not representatives or credentialed experts, should decide major questions directly.", color: "#D84315", components: [{ axis: "F6", direction: -1, weight: 1 }, { axis: "F5", direction: -1, weight: 0.8 }, { axis: "F4", direction: -1, weight: 0.8 }] },
  { id: "representative_constitutionalist", name: "Representative Constitutionalist", description: "Favors decisions made by deliberating representatives under strong constitutional limits and orderly procedure.", color: "#3949AB", components: [{ axis: "F6", direction: 1, weight: 1 }, { axis: "F4", direction: 1, weight: 1 }, { axis: "F1", direction: -1, weight: 0.5 }] },
  { id: "security_realist", name: "Security Realist", description: "Backs strong deterrence and readiness to use force, paired with order at home and sovereignty abroad.", color: "#7F0000", components: [{ axis: "F7", direction: 1, weight: 1 }, { axis: "C3", direction: -1, weight: 0.6 }, { axis: "C7", direction: -1, weight: 0.6 }] },
  { id: "principled_dove", name: "Principled Dove", description: "Opposes military force and coercive retaliation, favoring diplomacy, restraint, and repair over escalation.", color: "#0288D1", components: [{ axis: "F7", direction: -1, weight: 1 }, { axis: "F3", direction: 1, weight: 0.5 }, { axis: "C6", direction: 1, weight: 0.4 }] },
  { id: "liberal_internationalist", name: "Liberal Internationalist", description: "Supports binding international institutions and universal rights, and is willing to back them with collective force.", color: "#00695C", components: [{ axis: "C7", direction: 1, weight: 1 }, { axis: "C6", direction: 1, weight: 0.6 }, { axis: "F7", direction: 1, weight: 0.5 }] }
]
