#!/usr/bin/env bash
# Point `npm run dev` at the local Supabase stack.
#
# Writes .env.development.local from `supabase status`. Next.js gives that file
# priority over .env.local during `next dev` only, so production credentials
# you may keep in .env.local are never used for local development, and
# `next build` / `next start` ignore it entirely. The file is gitignored.
set -euo pipefail

cd "$(dirname "$0")/.."
SUPABASE="npx --yes supabase@${SUPABASE_CLI_VERSION:-2.120.0}"
TARGET=.env.development.local

status=$($SUPABASE status -o env 2>/dev/null) || {
  echo "Local Supabase is not running. Start it with: npm run db:start" >&2
  exit 1
}
value() { printf '%s\n' "$status" | sed -n "s/^$1=\"\{0,1\}\([^\"]*\)\"\{0,1\}$/\1/p"; }

API_URL=$(value API_URL)
ANON_KEY=$(value ANON_KEY)
SERVICE_ROLE_KEY=$(value SERVICE_ROLE_KEY)
if [[ -z "$API_URL" || -z "$ANON_KEY" || -z "$SERVICE_ROLE_KEY" ]]; then
  echo "Could not read API_URL / ANON_KEY / SERVICE_ROLE_KEY from supabase status." >&2
  exit 1
fi

# Keep any AI analysis settings already in the file; replace only Supabase keys.
extra=""
if [[ -f "$TARGET" ]]; then
  extra=$(grep -vE '^(# Generated by|NEXT_PUBLIC_SUPABASE_URL|NEXT_PUBLIC_SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY|NEXT_PUBLIC_SITE_URL)' "$TARGET" || true)
fi

{
  echo "# Generated by scripts/local-env.sh for the LOCAL Supabase stack. Do not use in production."
  echo "NEXT_PUBLIC_SUPABASE_URL=$API_URL"
  echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY"
  echo "SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY"
  echo "NEXT_PUBLIC_SITE_URL=http://localhost:3000"
  if [[ -n "$extra" ]]; then
    printf '%s\n' "$extra"
  else
    echo "AI_ANALYSIS_ENABLED=false"
  fi
} > "$TARGET"

echo "Wrote $TARGET -> $API_URL"
